@section('title','Trang chủ')
@extends('layouts.template')

@section('breadcrumb')

   <h1>DANH SÁCH KHU VỰC</h1>

    {{ Breadcrumbs::render('area') }}

@endsection

@section('content')

<section class="section" id="area-to-user">

   <div class="row">
        <div class="col-12">

            <div class="row">
                <div class="col-sm-6">
                    <div id="modules">
                        @foreach($areas as $area)
                            <p class="drag mb-1">
                                <a id="{{ $area->id }}" class="btn btn-secondary ">{{ $area->name }}</a>
                            </p>
                        @endforeach
                    </div>
                </div>

                <div class="col-sm-6">
                    <form method="post" action="" id="form-user-to-area">
                        {{ csrf_field() }}
                        <div class="card mb-2">
                            <div class="card-body">
                                <h5 class="card-title">Chọn khu vực và nhân viên</h5>
                                <!-- Default Accordion -->
                                @foreach($users as $user)
                                    <div class="accordion" id="accordionExample{{$user->id}}">
                                        <div class="accordion-item">
                                            <h2 class="accordion-header" id="headingOne{{$user->id}}">
                                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{$user->id}}" aria-expanded="false" aria-controls="collapseOne{{$user->id}}">
                                                {{$user->username}}
                                                </button>
                                            </h2>
                                            <div id="collapseOne{{$user->id}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample{{$user->id}}">
                                                <div class="accordion-body">
                                                    <div class="dropzone_area" id="dropzone{{$user->id}}">

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>

                        <a href="#" id="btn-submit-user" class="btn btn-primary d-flex justify-content-center">Save</a>
                    </form>
                </div>
            </div>
        </div>
   </div>
</section>
@endsection

@push('scripts')
<script>
    $('.drag').draggable({
        appendTo: 'body',
        helper: 'clone'
    });

    $('.dropzone_area').droppable({
        activeClass: 'active',
        hoverClass: 'hover',
        accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
        drop: function (e, ui) {
            var $el = $('<div class="drop-item"><span>' + ui.draggable.html() + '</span></div>');
            $el.append($('<button type="button" class="btn-close" aria-label="Close"</span></button>').click(function () { $(this).parent().detach(); }));
            $(this).append($el);
        }
    }).sortable({
        items: '.drop-item',
        sort: function() {
            $( this ).removeClass( "active" );
        }
    });

</script>

<script>


$( "#btn-submit-user" ).click(function() {

    var listArea = [];
    $(".accordion").each(function(index) {
        var username = $(this).find('.accordion-header').text().trim();
        var area = {};

        var listAreaEl = $(this).find('.drop-item');

        $(listAreaEl).each(function(i) {
            let that = this;
            area.id_area = $(that).find('a').attr('id');
            area.name_area = $(that).find('a').text().trim();

            listArea.push(JSON.stringify(area));
        });
    });
console.log(listArea);
    var input = $("<input>").attr("type", "hidden").attr("name", "area_user_data").val(listArea);
    $('#form-user-to-area').append(input);

    // $( "#form-user-to-area" ).submit();
});



</script>

@endpush

@push('css')
    <style>
    #area-to-user #modules {
        padding: 20px;
        background: #eee;
        margin-bottom: 20px;
        z-index: 1;
        border-radius: 10px;
    }
    /* area-to-user */
    #area-to-user .dropzone_area {
        padding: 10px;
        background: #eee;
        min-height: 100px;
        margin-bottom: 20px;
        z-index: 0;
        border-radius: 10px;
    }

    #area-to-user .active {
        outline: 1px solid red;
    }

    #area-to-user .hover {
        outline: 1px solid blue;
    }

    #area-to-user .drop-item {
        cursor: pointer;
        margin-bottom: 10px;
        background-color: rgb(255, 255, 255);
        padding: 5px 10px;
        border-radisu: 3px;
        border: 1px solid rgb(204, 204, 204);
        position: relative;
    }

    #area-to-user .drop-item .remove {
        position: absolute;
        top: 4px;
        right: 4px;
    }
    #area-to-user .btn-close {
        position: absolute;
        top: 0;
        right: 0;
        height: 100%;
        font-size: 3rem;
        padding: 0;
    }
</style>
@endpush
